config/routes.rb
Rails.application.routes.draw do
# user用
# URL /customers/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

#ゲストログイン用
devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
end

 #user側のルーティング設定
 scope module: :user do
   root to: "homes#top"
   get '/about' => 'homes#about', as: 'about'
   get "search" => "searches#search"
   resources :films do
     resource :favorites, only: [:create, :destroy]
     resources :film_comments, only: [:create, :destroy]
   end

   get '/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
   patch '/withdraw' => 'users#withdraw', as: 'withdraw'
   resources :users, only: [:index, :show, :edit, :update]

   get "/films/genre_search/:id" => "films#genre_search",as: 'films_genre_search'
 end

 #管理者側のルーティング設定
 namespace :admin do
   root to: "homes#top"
   resources :genres, only: [:index, :create, :edit, :update, :destroy]
   resources :users, only: [:index, :show, :edit, :update]
   resources :films, only: [:index, :show, :destroy] do
     resources :film_comments, only: [:destroy]
   end
 end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :films, dependent: :destroy
  has_many :film_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :name
    validates :name_kana
    validates :sex
    validates :age_group
  end

  validates :is_valid, inclusion: { in: [true, false] }

  has_one_attached :profile_image

  #user登録する際、画像がない場合に代わりにあらかじめ用意した画像を表示する記述
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  #ゲストログイン用の記述
  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.name_kana = "guestuser"
      user.sex = "man"
      user.age_group = "early20"
    end
  end

 enum sex: { man: 0, woman: 1 }
 enum age_group: { under19: 0, early20: 1, older20: 2, early30: 3, older30: 4, early40: 5, older40: 6, early50: 7, older50: 8, over61: 9  }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :user_find, only: [:show, :edit, :update]

  def show
  end

  def index
    @users = User.page(params[:page])
  end


  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: "変更が完了しました"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :name_kana, :sex, :age_group, :email, :is_valid)
  end

  def user_find
     @user = User.find(params[:id])
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
    @film = Film.find(params[:film_id])
    favorite = current_user.favorites.new(film_id: @film.id)
    favorite.save
    #redirect_to request.referer
  end

  def destroy
    @film = Film.find(params[:film_id])
    favorite = current_user.favorites.find_by(film_id: @film.id)
    favorite.destroy
   # redirect_to request.referer
  end

end

app/controllers/user/film_comments_controller.rb
class User::FilmCommentsController < ApplicationController

  def create
    @film = Film.find(params[:film_id])
    @film_comment = FilmComment.new(film_comment_params)
    @film_comment.user_id = current_user.id
    @film_comment.film_id = @film.id
    @film_comment.save
    #redirect_to request.referer
  end

  def destroy
    @film = Film.find(params[:film_id])
    film_comment=FilmComment.find_by(id: params[:id], film_id: params[:film_id])
    film_comment.destroy
    #redirect_to request.referer
  end



  private

  def film_comment_params
    params.require(:film_comment).permit(:comment)
  end


end

app/controllers/user/films_controller.rb
class User::FilmsController < ApplicationController
  before_action :authenticate_user!
  before_action :film_find, only: [:show, :edit, :update, :destroy]

  def new
    @film = Film.new
    @genres = Genre.all
  end

  def create
    @film = Film.new(film_params)
    @film.user_id = current_user.id
    if @film.save
      redirect_to film_path(@film.id), notice: "投稿できました！"
    else
      @genres = Genre.all
      render :new
    end
  end

  def index
    if params[:latest]
      @films = Film.latest.page(params[:page])
    elsif params[:old]
      @films = Film.old.page(params[:page])
    elsif params[:favorited_count]
      films = Film.favorited_count
      @films = Kaminari.paginate_array(films).page(params[:page])
    elsif params[:star_count]
      @films = Film.star_count.page(params[:page])
    else
      @films = Film.page(params[:page])
    end
    @genres = Genre.all
    @film_count = Film.all
  end

  def show
    @user = @film.user
    @film_comment = FilmComment.new
  end

  def edit
    @genres = Genre.all
    if @film.user != current_user
       redirect_to films_path
    end
  end

  def update
    if @film.update(film_params)
      redirect_to film_path(@film.id), notice: "編集できました！"
    else
      @genres = Genre.all
      render :edit
    end
  end

  def destroy
    @film.destroy
    redirect_to films_path
  end

  def genre_search
    @genres = Genre.all
    @genre = Genre.find(params[:id])
    @films = @genre.films.page(params[:page])
    genres_list(params)
  end

  def genres_list(params)
    if params[:latest]
      @films = @genre.films.latest.page(params[:page])
    elsif params[:old]
      @films = @genre.films.old.page(params[:page])
    elsif params[:favorited_count]
      films = @genre.films.favorited_count
      @films = Kaminari.paginate_array(films).page(params[:page])
    elsif params[:star_count]
      @films = @genre.films.star_count.page(params[:page])
    end
  end

  private

  def film_params
    params.require(:film).permit(:title, :body, :genre_id, :image, :star)
  end

  def film_find
    @film = Film.find(params[:id])
  end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_sign_up_params, only: [:create]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_up_path_for(resource)
      user_path(current_user)
  end

  protected


    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :sex, :age_group])
    end

end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
   before_action :authenticate_user!

  def search
    films = Film.search(params[:keyword]).page(params[:page])
    if params[:latest]
      @films = films.latest.page(params[:page])
    elsif params[:old]
      @films = films.old.page(params[:page])
    elsif params[:star_count]
      @films = films.star_count.page(params[:page])
    else
      @films = films
    end
    @keyword = params[:keyword]
    @films_count = Film.search(params[:keyword]).all
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  before_action :user_state, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
      user_path(current_user)
  end

  def after_sign_out_path_for(resource)
      about_path
  end

  protected
    # 退会しているかを判断するメソッド
  def user_state
    ## 【処理内容1】 入力されたemailからアカウントを1件取得
    @user = User.find_by(email: params[:user][:email])
    ## アカウントを取得できなかった場合、このメソッドを終了する
    return if !@user
    ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
    if @user.valid_password?(params[:user][:password]) && !@user.is_valid
       redirect_to new_user_registration_path, notice: "退会済みです。新規会員登録を行なってください。"
      ## 【処理内容3】
    end
  end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @films = @user.films.page(params[:page])
    films_list(params)
  end

  #show画面個人別投稿一覧(新しい順・古い順・いいね順・評価順）で表示する
  def films_list(params)
    if params[:latest]
      @films = @user.films.latest.page(params[:page])
    elsif params[:old]
      @films = @user.films.old.page(params[:page])
    elsif params[:favorited_count]
      films = @user.films.favorited_count
      @films = Kaminari.paginate_array(films).page(params[:page])
    elsif params[:star_count]
      @films = @user.films.star_count.page(params[:page])
    end
  end

  def index
    @users = User.page(params[:page])
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "編集が完了しました"
    else
      render :edit
    end
  end

  def unsubscribe
    @user = current_user
  end

  def withdraw
    @user = current_user
    @user.update(is_valid: false)
    reset_session
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:name, :name_kana, :sex, :age_group, :email, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/film_comments_helper.rb
module User::FilmCommentsHelper
end

app/helpers/user/films_helper.rb
module User::FilmsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/user/users/_index.html.erb
<table class='table table-hover'>
  <thead class="thead-light">
    <tr>
      <th>ステータス</th>
      <th>プロフィール画像</th>
      <th>名前</th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%if user.is_valid? == true %>
           <span class="text-success">有効</span>
          <% else %>
           <span class="text-danger">退会済み</span>
          <% end %>
        </td>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td>
          <%= link_to user_path(user.id) do %>
            <%= user.name %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate users, theme: 'twitter-bootstrap-4',pagination_class: "pagination-sm",nav_class: "d-inline-b" %>

app/views/user/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>名前</th>
	  <td><%= user.name %></td>
  </tr>
  <tr>
	  <th>性別</th>
	  <td><%= user.sex_i18n %></td>
  </tr>
  <tr>
    <th>年齢層</th>
    <td><%= user.age_group_i18n %></td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td>
      <%if user.is_valid? == true %>
       <span class="text-success">有効</span>
      <% else %>
       <span class="text-danger">退会済み</span>
      <% end %>
    </td>
  </tr>
</table>
<% if user.name != "guestuser" %>
 <% if current_user == user %>
  <div class='row'>
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-edit"></i>
    <% end %>
  </div>
 <% end %>
<% end %>
<div class='row mt-4'>
  <p class="mx-auto">☆Share your recommendations☆</p>
  <%= link_to "投稿する", new_film_path, class: "btn btn-outline-info btn-block mt-1" %>
</div>

app/views/user/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2 class="text-center"><%= @user.name %>さんの会員情報編集</h2>
      <%= render 'layouts/errors', obj: @user %>
      <%= form_with model: @user do |f| %>

       <table class ="table table-borderless">
         <tr>
           <th><%= f.label :"名前" %></th>
           <td><%= f.text_field :name, class: "form-control w-75" %></td>
         </tr>

         <tr>
           <th><%= f.label :"フリガナ" %></th>
           <td><%= f.text_field :name_kana, class: "form-control w-75" %></td>
         </tr>

         <tr>
           <th><%= f.label :"メールアドレス" %></th>
           <td><%= f.email_field :email, class: "form-control w-75" %></td>
         </tr>

         <tr>
           <th><%= f.label :"性別" %></th>
           <td><%= f.select :sex, User.sexes.keys.map {|k| [I18n.t("enums.user.sex.#{k}"), k]}, {include_blank: "--選択してください--"}, class: "form-control", style: "width: 30%;" %></td>
         </tr>

         <tr>
           <th><%= f.label :"年齢層" %></th>
           <td><%= f.select :age_group, User.age_groups.keys.map {|k| [I18n.t("enums.user.age_group.#{k}"), k]}, {include_blank: "--選択してください--"}, class: "form-control", style: "width: 45%" %></td>
         </tr>

         <tr>
           <th style="width: 35%;"><%= f.label :"プロフィール画像" %></th>
           <td><%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %></td>
         </tr>

         <tr>
           <td><%= f.submit "編集を保存", class: "btn btn-outline-success" %></td>
         </tr>

         <tr>
           <td><%= link_to "退会する", unsubscribe_path, class: "btn btn-danger", style: "width: 86%" %></td>
         </tr>
       </table>
      <% end %>
    </div>
  </div>
</div>

app/views/user/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h3>あなたの会員情報</h3>
      <%= render 'info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h3>会員一覧</h3>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/user/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h3>
        <% if @user == current_user %>
         あなたの会員情報
        <% else %>
         <%= @user.name %>さんの<br>
         会員情報
        <% end %>
      </h3>
      <%= render 'info', user: @user %>
    </div>
    <div class='col-md-9'>
      <h3>
        <% if @user == current_user %>
         あなたの投稿一覧
        <% else %>
         <%= @user.name %>さんの投稿一覧
        <% end %>
      </h3>
      <h6>(<%= @user.films.count %>件)</h6>
      <p>
        <%= link_to '新しい順', user_path(@user.id, latest: "true") %>
        |<%= link_to '古い順', user_path(@user.id, old: "true") %>
        |<%= link_to 'いいね順', user_path(@user.id, favorited_count: "true") %>
        |<%= link_to '評価の高い順', user_path(@user.id, star_count: "true") %>
      </p>
      <%= render 'user/films/index',films: @films %>
    </div>
  </div>
</div>

app/views/user/users/unsubscribe.html.erb
<div class='container'>
  <div class='row'>
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-5">
        <h4 class="text-center"><strong>本当に退会しますか？</strong></h4>
     </div>
  </div>

   <div class='row'>
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-5">
       <p class="ml-2">
         退会すると、このアカウントで再度ログインすることが<br>
         できなくなります。<br>
         退会する場合は、「退会する」をクリックしてください。
       </p>
     </div>
  </div>

  <div class='row'>
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-3">
       <%= link_to "退会しない", user_path(current_user), class: "btn btn-outline-primary mx-5" %>
       <%= link_to "退会する", withdraw_path, method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger mx-5" %>
     </div>
  </div>
</div>